# -*- coding: utf-8 -*-
"""Aprendizado de maquina II - nao supervisionado

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJv1AkxUSGybjZEjicXTKeyol1i-TWzn
"""

import cv2
import os
import sys
import random
import numpy as np

class person:
  pass
class PCA:

pca = PCA(0.9 9) # variância explicada de 0.99
lower_dimension_data = pca.fit_transform(X)
lower_dimension_data.shape

pca = PCA(0.99) # variância explicada de 0.99
lower_dimension_data = pca.fit_transform(X)
lower_dimension_data.shape

def load_data_set (path, train, test, p)

path = "./"
train = []
test = []

p = 7

PCA.load_data_set (path, train, test, p)

start = 10
end = 20

for k in range (star, end)

print (k, "componentes principais, acurácia") + {"%"}